In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [42]:
data = pd.read_csv('Counties2016.csv')

In [43]:
data.head(5)

,State,County,FIPS,Density,White,MHI,Bachelors,2012D,2012R,2012O,2016D,2016R,2016O
0,Alabama,Autauga,1001,92.931162,0.750462,58343,0.250,6363,17379,231,5936,18172,865
1,Alabama,Baldwin,1003,130.654556,0.831589,56607,0.307,18424,66016,1051,18458,72883,3874
2,Alabama,Barbour,1005,29.177968,0.462411,32490,0.120,5912,5550,55,4871,5454,144
3,Alabama,Bibb,1007,36.262006,0.745526,45795,0.132,2202,6132,86,1874,6738,207
4,Alabama,Blount,1009,89.204070,0.874993,48253,0.131,2970,20757,333,2156,22859,573

In [44]:
data['2012Total'] = data['2012D'] + data['2012R'] + data['2012O']
data['2012DPCT'] = data['2012D'] / data['2012Total']
data['2012RPCT'] = data['2012R'] / data['2012Total']
data['2012OPCT'] = data['2012O'] / data['2012Total']

In [45]:
data['2012Margin'] = data['2012RPCT'] - data['2012DPCT']

In [46]:
data['2016Total'] = data['2016D'] + data['2016R'] + data['2016O']
data['2016DPCT'] = data['2016D'] / data['2016Total']
data['2016RPCT'] = data['2016R'] / data['2016Total']
data['2016OPCT'] = data['2016O'] / data['2016Total']

In [47]:
data['2016Margin'] = data['2016RPCT'] - data['2016DPCT']
data['Diff_12_16'] = data['2016Margin'] - data['2012Margin']

In [48]:
#export cleaned data as CSV
data.to_csv('2020_cleaned.csv')

In [49]:
data_2020 = pd.read_csv('2020_cleaned.csv')

In [50]:
#Correlation between density, white population, median household income, bachelor's degree holders, and difference
var1 = ['Density', 'White', 'MHI', 'Bachelors', 'Diff_12_16']
data_2020[var1].corr()

             Density     White       MHI  Bachelors  Diff_12_16
Density     1.000000 -0.158125  0.165836   0.241984   -0.100993
White      -0.158125  1.000000  0.127930   0.011755    0.330843
MHI         0.165836  0.127930  1.000000   0.718579   -0.248764
Bachelors   0.241984  0.011755  0.718579   1.000000   -0.376285
Diff_12_16 -0.100993  0.330843 -0.248764  -0.376285    1.000000

In [51]:
model_lin = sm.OLS.from_formula("Diff_12_16 ~ Density + White + MHI + Bachelors", data=data_2020)
result_lin = model_lin.fit()
result_lin.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             Diff_12_16   R-squared:                       0.257
Model:                            OLS   Adj. R-squared:                  0.256
Method:                 Least Squares   F-statistic:                     268.5
Date:                Sun, 01 Nov 2020   Prob (F-statistic):          1.90e-198
Time:                        23:32:19   Log-Likelihood:                 1282.0
No. Observations:                3112   AIC:                            -2554.
Df Residuals:                    3107   BIC:                            -2524.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0605      0.015      4.040      0.000       0.031       0.090
Density     5.007e-06   1.67e-06      3.006      0.003    1.74e-06    8.27e-06
White          0.3260      0.015     21.855      0.000       0.297       0.355
MHI        -5.591e-07   3.12e-07     -1.791      0.073   -1.17e-06    5.29e-08
Bachelors     -0.7275      0.045    -16.003      0.000      -0.817      -0.638
==============================================================================
Omnibus:                     2118.846   Durbin-Watson:                   0.800
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            36542.032
Skew:                           3.025   Prob(JB):                         0.00
Kurtosis:                      18.659   Cond. No.                     8.34e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.34e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""