In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
votes = pd.read_csv('./ElectionData/Michigan.csv', low_memory=False)
votes.head()

,State,Year,Office,County,D1#,R#,SD#,D2#,AS#,Nat.#,...,CON#,SD#.1,PU#,Tisch #,W/I7#,W/I8#,W/I9#,SqD#,CD#,T#
0,Michigan,1876,President,Alcona,162.0,155,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Michigan,1876,President,Allegan,3169.0,4281,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Michigan,1876,President,Alpena,635.0,629,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Michigan,1876,President,Antrim,280.0,475,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Michigan,1876,President,Baraga,232.0,218,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
votes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10440 entries, 0 to 10439
Data columns (total 69 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   State    10440 non-null  object
 1   Year     10440 non-null  int64
 2   Office   10440 non-null  object
 3   County   10440 non-null  object
 4   D1#      3136 non-null   float64
 5   R#       10440 non-null  int64
 6   SD#      166 non-null    float64
 7   D2#      83 non-null     float64
 8   AS#      76 non-null     float64
 9   Nat.#    83 non-null     float64
 10  Wor.#    332 non-null    float64
 11  AF#      83 non-null     float64
 12  Lib.#    83 non-null     float64
 13  TC#      249 non-null    float64
 14  NP#      83 non-null     float64
 15  HR#      498 non-null    float64
 16  Cit.#    83 non-null     float64
 17  GB#      230 non-null    float64
 18  FL#      166 non-null    float64
 19  Proh.#   4222 non-null   float64
 20  Labor#   407 non-null    float64
 21  UL#      83 non-null     float64
 22  Pop.#    333 non-null    float64
 23  SW#      2739 non-null   float64
 24  S#       1577 non-null   float64
 25  Comm.#   664 non-null    float64
 26  SL#      5312 non-null   float64
 27  SE#      166 non-null    float64
 28  CW#      249 non-null    float64
 29  ST#      83 non-null     float64
 30  Prog.#   415 non-null    float64
 31  U#       83 non-null     float64
 32  AI#      1411 non-null   float64
 33  Ind.#    83 non-null     float64
 34  Tisch#   166 non-null    float64
 35  I1#      498 non-null    float64
 36  I2#      249 non-null    float64
 37  I3#      166 non-null    float64
 38  I4#      83 non-null     float64
 39  Ref.#    332 non-null    float64
 40  NL#      1494 non-null   float64
 41  G#       1992 non-null   float64
 42  L#       2988 non-null   float64
 43  WL#      498 non-null    float64
 44  UC#      83 non-null     float64
 45  W/I#     3404 non-null   float64
 46  W/I2#    1328 non-null   float64
 47  W/I3#    1162 non-null   float64
 48  W/I4#    747 non-null    float64
 49  W/I5#    415 non-null    float64
 50  W/I6#    249 non-null    float64
 51  D#       7304 non-null   float64
 52  FN#      166 non-null    float64
 53  WW#      415 non-null    float64
 54  I#       166 non-null    float64
 55  WAC#     83 non-null     float64
 56  W/I1#    3984 non-null   float64
 57  IND#     166 non-null    float64
 58  Am.#     830 non-null    float64
 59  CON#     166 non-null    float64
 60  SD#.1    83 non-null     float64
 61  PU#      166 non-null    float64
 62  Tisch #  83 non-null     float64
 63  W/I7#    166 non-null    float64
 64  W/I8#    166 non-null    float64
 65  W/I9#    83 non-null     float64
 66  SqD#     83 non-null     float64
 67  CD#      83 non-null     float64
 68  T#       1411 non-null   float64
dtypes: float64(64), int64(2), object(3)
memory usage: 5.5+ MB

In [4]:
votes = votes.fillna(0)

In [5]:
votes['Year'] = pd.to_numeric(votes['Year'])

In [6]:
votes.loc[:,'Total Votes'] = (votes.sum(axis=1)) - votes['Year']

In [7]:
pres = votes[votes['Office'] == 'President']

In [8]:
pres = pres.drop('Office', axis = 1)

In [9]:
pres['Year'] = pd.to_numeric(pres['Year'])

In [10]:
pres['PCT_DEM'] = (round(pres['D#']/pres['Total Votes'],4))*100

In [11]:
pres['PCT_REP'] = (round(pres['R#']/pres['Total Votes'],4))*100

In [12]:
pres['RD_DIFF'] = pres['PCT_REP'] - pres['PCT_DEM']

In [13]:
pres_pct = pres[['State', 'Year', 'County', 'RD_DIFF']]

In [14]:
pres_pct_2000 = pres_pct[pres_pct['Year'] >= 2000]

In [15]:
counties = ['Alger', 'Baraga', 'Chippewa', 'Delta', 'Dickinson', 'Gogebic', 'Houghton', 'Iron', 'Keweenaw', 'Luce', \
            'Mackinac', 'Marquette', 'Menominee', 'Ontonagon', 'Schoolcraft']

In [16]:
for c in counties:
    print(pres_pct_2000[pres_pct_2000['County'] == c])

          State  Year County  RD_DIFF
2556   Michigan  2000  Alger    49.06
2639   Michigan  2004  Alger    48.65
2722   Michigan  2008  Alger    46.06
2805   Michigan  2012  Alger    50.45
2888   Michigan  2016  Alger    57.22
10358  Michigan  2020  Alger    58.70
          State  Year  County  RD_DIFF
2561   Michigan  2000  Baraga    54.11
2644   Michigan  2004  Baraga    53.66
2727   Michigan  2008  Baraga    50.53
2810   Michigan  2012  Baraga    53.47
2893   Michigan  2016  Baraga    61.34
10363  Michigan  2020  Baraga    62.07
          State  Year    County  RD_DIFF
2571   Michigan  2000  Chippewa    52.43
2654   Michigan  2004  Chippewa    55.33
2737   Michigan  2008  Chippewa    49.48
2820   Michigan  2012  Chippewa    52.86
2903   Michigan  2016  Chippewa    58.65
10373  Michigan  2020  Chippewa    60.44
          State  Year County  RD_DIFF
2575   Michigan  2000  Delta    51.23
2658   Michigan  2004  Delta    50.32
2741   Michigan  2008  Delta    45.97
2824   Michigan  2012  Delta    52.59
2907   Michigan  2016  Delta    59.81
10377  Michigan  2020  Delta    62.39
          State  Year     County  RD_DIFF
2576   Michigan  2000  Dickinson    54.02
2659   Michigan  2004  Dickinson    57.08
2742   Michigan  2008  Dickinson    52.96
2825   Michigan  2012  Dickinson    59.82
2908   Michigan  2016  Dickinson    64.84
10378  Michigan  2020  Dickinson    65.80
          State  Year   County  RD_DIFF
2581   Michigan  2000  Gogebic    47.12
2664   Michigan  2004  Gogebic    46.56
2747   Michigan  2008  Gogebic    40.21
2830   Michigan  2012  Gogebic    45.24
2913   Michigan  2016  Gogebic    54.42
10383  Michigan  2020  Gogebic    55.58
          State  Year    County  RD_DIFF
2585   Michigan  2000  Houghton    55.54
2668   Michigan  2004  Houghton    56.08
2751   Michigan  2008  Houghton    50.72
2834   Michigan  2012  Houghton    53.36
2917   Michigan  2016  Houghton    53.77
10387  Michigan  2020  Houghton    56.00
          State  Year County  RD_DIFF
2590   Michigan  2000   Iron    47.95
2673   Michigan  2004   Iron    49.52
2756   Michigan  2008   Iron    47.83
2839   Michigan  2012   Iron    53.63
2922   Michigan  2016   Iron    61.66
10392  Michigan  2020   Iron    62.05
          State  Year    County  RD_DIFF
2596   Michigan  2000  Keweenaw    55.10
2679   Michigan  2004  Keweenaw    54.27
2762   Michigan  2008  Keweenaw    53.62
2845   Michigan  2012  Keweenaw    55.60
2928   Michigan  2016  Keweenaw    56.76
10398  Michigan  2020  Keweenaw    55.36
          State  Year County  RD_DIFF
2602   Michigan  2000   Luce    58.36
2685   Michigan  2004   Luce    61.82
2768   Michigan  2008   Luce    54.38
2851   Michigan  2012   Luce    60.86
2934   Michigan  2016   Luce    67.77
10404  Michigan  2020   Luce    70.14
          State  Year    County  RD_DIFF
2603   Michigan  2000  Mackinac    54.81
2686   Michigan  2004  Mackinac    56.16
2769   Michigan  2008  Mackinac    50.99
2852   Michigan  2012  Mackinac    55.53
2935   Michigan  2016  Mackinac    60.94
10405  Michigan  2020  Mackinac    61.27
          State  Year     County  RD_DIFF
2606   Michigan  2000  Marquette    43.10
2689   Michigan  2004  Marquette    45.22
2772   Michigan  2008  Marquette    38.80
2855   Michigan  2012  Marquette    42.06
2938   Michigan  2016  Marquette    44.09
10408  Michigan  2020  Marquette    43.37
          State  Year     County  RD_DIFF
2609   Michigan  2000  Menominee    52.99
2692   Michigan  2004  Menominee    52.04
2775   Michigan  2008  Menominee    43.85
2858   Michigan  2012  Menominee    50.73
2941   Michigan  2016  Menominee    61.92
10411  Michigan  2020  Menominee    64.31
          State  Year     County  RD_DIFF
2620   Michigan  2000  Ontonagon    59.55
2703   Michigan  2004  Ontonagon    53.96
2786   Michigan  2008  Ontonagon    46.92
2869   Michigan  2012  Ontonagon    53.86
2952   Michigan  2016  Ontonagon    60.18
10422  Michigan  2020  Ontonagon    61.89
          State  Year       County  RD_DIFF
2631   Michigan  2000  Schoolcraft    49.74
2714   Michigan  2004  Schoolcraft    51.05
2797   Michigan  2008  Schoolcraft    47.47
2880   Michigan  2012  Schoolcraft    52.75
2963   Michigan  2016  Schoolcraft    61.19
10431  Michigan  2020  Schoolcraft    65.12